# Generated by Django 4.1.7 on 2023-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailvar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fack_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('Confirm_Password', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
